version: '3'
services:
  mongo:
    image: mongo:5.0.9-focal
    ports:
      - "27017:27017"
      - "28017:28017"
    command: ["--auth", "--oplogSize", "100"]
  rabbitmq:
    image: bitnami/rabbitmq:3.9.28
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      - RABBITMQ_USERNAME=admin
      - RABBITMQ_PASSWORD=foobar
      - RABBITMQ_PLUGINS=rabbitmq_management
      -


