logging:
  version: 1
  formatters:
     json: 
       class: pythonjsonlogger.jsonlogger.JsonFormatter
       # https://docs.python.org/3/library/logging.html#logrecord-attributes
       format: "{asctime} {levelname} {hostname} {message} {task_id} {task_name}"
       style: "{"
  filters:
     hostname:
       (): omegaml.util.hostnameFilter
     task:
       (): omegaml.util.taskFilter
  handlers:
     console:
       class: logging.StreamHandler
       stream: ext://sys.stdout
       formatter: json
       filters:
          - task
          - hostname 
  loggers:
     root:
        handlers: 
          - console
        level: INFO
     celery.task:
        handlers:
          - console
 

